### ISSUE TITLE
Erro when i access url http://localhost:3000/users

### ISSUE THREAD

**Issue by nicholasess** [aseemk/node-neo4j-template#17]
I have a database neo4j empty and when i click in View all users, put in terminal error:

TypeError: Object #<Object> has no method 'split'.

What can i need to do?

**Comment by stillmatic** [comment]
had this problem too, work around for future reference:

from neo4j gui > settings > 'open command prompt'

then:
```
> neo4jshell
> start
```

**Comment by aseemk** [comment]
Very strange guys, I haven't encountered this. Can you tell me:

- Node version (`node --version`)
- Neo4j version
- Node-Neo4j version (`npm ls neo4j`)

I'm working on an update to this template app for node-neo4j v2: pull #18.

The code is done, I just need to update the docs (but they're mostly unchanged). Can you try it out and tell me if you get this same error there?

**Comment by stillmatic** [comment]
running windows 8.1 if that helps
```
node --version
v0.10.38

npm ls neo4j
NodeNeo4jTemplate@0.0.1
└── neo4j@1.1.1
```
and neo4j 2.2.2

**Comment by aseemk** [comment]
Cool, given that you're running Neo4j 2.2, it probably has to do with auth, which node-neo4j v2 adds support for. Looking forward to seeing what you find.

**Comment by aseemk** [comment]
I just merged the v2 branch into master, so you should also see this problem go away if you update to the last master.

**Comment by aseemk** [comment]
(You'll need to re-run `npm install`.)

**Comment by stillmatic** [comment]
hmm...not seeing where to edit user/pw for neo4j?

**Comment by stillmatic** [comment]
it works now

**Comment by aseemk** [comment]
Great! I'll go ahead close this. Anyone should feel free to re-open if still an issue.
