### ISSUE TITLE
need a hint: how to query multiple nodes?

### ISSUE THREAD

**Issue by graphadvantage** [aseemk/node-neo4j-template#20]
Hi Aseem,

is there a simple way to return (and query the properties of) multiple nodes?  Template works great for single nodes, looking for a method to handle multiple nodes from a cypher query.  I can create callback variables for each node...seems like there should be a better way

```
User.get = function (username, callback) {
    var query = [
        'MATCH (user:User {username: {username}})-[:WATCHED]->(movie:MOVIE)',
        'RETURN user, movie',
    ].join('\n')
    var params = {
        username: username,
    };
    db.cypher({
        query: query,
        params: params,
    }, function (err, results) {
        if (err) return callback(err);
        if (!results.length) {
            err = new Error('No such user with username: ' + username);
            return callback(err);
        }
        var user = new User(results[0]['user']);
        var movie = new User(results[0]['movie']);
        callback(null, user, movie);
    });
};
```

Thanks!  Michael

**Comment by aseemk** [comment]
Hey @qosmy-michael, sorry for the delay here!

`results` is an array of Cypher result rows, so if your Cypher query matches and returns multiple nodes, you can simply get all of them via that `results` array.

(So i.e. don't index `[0]`; instead, iterate over all `results`.)

You can find examples of this in [`User.getAll`](https://github.com/aseemk/node-neo4j-template/blob/47528b307b815ac432bcfb865acfa86b6159e6c9/models/user.js#L278-L293) and [`User.prototype.getFollowingAndOthers`](https://github.com/aseemk/node-neo4j-template/blob/47528b307b815ac432bcfb865acfa86b6159e6c9/models/user.js#L210-L250).

Hope that helps! Feel free to re-open if something is still unclear.

**Comment by qosmy-michael** [comment]
Hi Aseem!

Thanks for getting back to me –  here’s how I ended up doing it.  The challenge was to get specific properties from different labeled nodes across our schema.  I ended up leveraging Cypher’s ability to return string literals to compose node-like JSON output , and passed into this the specific node properties we needed from the various collection variables.  Each entry is indexed by the ID of one of the nodes, and a single array (q) is returned.   Each property is then prototyped, rendering it accessable to the rest of the app.

I’m sure there’s a more elegant way to do this…LMK what you think.

Thanks

Michael


Review.getAll = function (callback) {
    var query = [
        'MATCH (q:Request)-[:HAS_RATING]-(r:Rating)-[:HAS_REVIEW]-(rv:Review)',
        'MATCH (q)-[:HAS_REQUEST]-(i:Issue)-[:CREATED]-(c:Consumer)',
        'MATCH (q)-[:HAS_CONTACT]-(p:BusinessContact)-[:HAS_CONTACTINFO]-(d:BusinessDepartment)-[:HAS_DEPARTMENT]-(b:Business)',
        'WHERE q.duration >= 60',
        //-'AND NOT c.email IN ["michael@qosmy.com","michaeldmoorephd@gmail.com","brin@qosmy.com","dan.rathbone@gmail.com","ben@scarybee.com"]',
        'RETURN q.createTime,r,rv,i,c,p,d,b,',
        '{ _id: ID(q), ',
            'labels:["ReviewData"], ',
            'properties: ',
            '{ ',
            'QID: q.QID,',
            'createTime: q.createTime,',
            'duration: q.duration,',
            'route: q.route,',
            'latency: q.latency,',
            'bandwidth: q.bandwidth,',
            'UUID: q.UUID,',
            'firstName: c.firstName,',
            'lastName: c.lastName,',
            'businessName: b.businessName,',
            'countRatings: b.countRatings,',
            'gotHelpPercentage: b.gotHelpPercentage,',
            'ratingsAverage: b.ratingsAverage,',
            'category: b.category,',
            'departmentName: d.departmentName,',
            'countRatingsDept: d.countRatings,',
            'gotHelpPercentageDept: d.gotHelpPercentage,',
            'ratingsAverageDept: d.ratingsAverage,',
            'contactInfo: p.contactInfo,',
            'gotHelp: r.gotHelp,',
            'politeAndCourteous: r.politeAndCourteous,',
            'promptAndEfficient: r.promptAndEfficient,',
            'informedAndUnderstandable: r.informedAndUnderstandable,',
            'kindAndEmpathetic: r.kindAndEmpathetic,',
            'stars: (TOINT(CASE WHEN r.gotHelp = true THEN 1 ELSE 0 END) + ',
                    'TOINT(CASE WHEN r.politeAndCourteous = true THEN 1 ELSE 0 END) + ',
                    'TOINT(CASE WHEN r.promptAndEfficient = true THEN 1 ELSE 0 END) + ',
                    'TOINT(CASE WHEN r.informedAndUnderstandable = true THEN 1 ELSE 0 END) + ',
                    'TOINT(CASE WHEN r.kindAndEmpathetic = true THEN 1 ELSE 0 END)),',
            'publishedToFacebook: rv.publishedToFacebook,',
            'publishedToTwitter: rv.publishedToTwitter,',
            'sentimentScore: rv.sentimentScore,',
            'reviewText: rv.reviewText',
        '}} AS q',
        'ORDER BY q.createTime DESC',
        'LIMIT 25',
    ].join('\n');

    //-- console.log(query);

    db.cypher({
        query: query,
    }, function (err, results) {
        if (err) return callback(err);
        var requests = results.map(function (result) {
            return new Review(result['q']);
        });
        callback(null, requests);

        //console.log(requests);
    });
};


Thanks,

Michael

Michael D. Moore, Ph.D.
Founder/CEO
Qosmy, Inc.
m<mailto:michael@qosmy.com>ichael@qosmy.com<mailto:michael@qosmy.com>
415 516 0255
Skype michael.qosmy

[cid:358744A1-05BF-4C55-95C7-D93B7C803295]

“You Deserve to be Heard!”

Qosmy.com<http://qosmy.com>

Get Qosmy for iOS at the App Store<https://itunes.apple.com/us/app/qosmy/id962940693?mt=8&at=&ct=&ign-mpt=uo%3D4>
